# Nama file: docker-compose.testing.yml
version: '3.9'

services:
  # Nama service diubah untuk menghindari konflik
  backend_testing:
    build: .
    # Container name diubah
    container_name: backend_rental_testing
    ports:
      # Port diubah dari 8000 menjadi 8001 agar tidak bentrok dengan service lama
      - "8001:8000"
    env_file:
      # Menggunakan file environment yang berbeda, misal .env.testing
      - .env.testing
    depends_on:
      # Menyesuaikan dengan nama service db yang baru
      db_testing:
        condition: service_healthy
    volumes:
      # Menggunakan folder storage yang berbeda untuk testing
      - /var/www/html/rental-storage-testing:/var/www/html/rental-storage
    restart: unless-stopped
    networks: 
      # Menggunakan network yang berbeda
      - rental_testing_network

  # Nama service database diubah
  db_testing:
    image: postgres:15
    # Container name diubah
    container_name: db_rental_testing
    environment:
      # --- KREDENSIAL DATABASE BARU UNTUK TESTING ---
      POSTGRES_USER: rental_testing
      POSTGRES_PASSWORD: rental_testing_password # Ganti dengan password yang aman
      POSTGRES_DB: rental_testing
    ports:
      # Port diubah dari 5432 menjadi 5433 agar tidak bentrok
      - "5433:5432"
    volumes:
      # Menggunakan volume data yang berbeda untuk testing
      - rental_pgdata_testing:/var/lib/postgresql/data
    healthcheck:
      # Test disesuaikan dengan user baru
      test: ["CMD-SHELL", "pg_isready -U rental_testing"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks: 
      # Menggunakan network yang berbeda
      - rental_testing_network

volumes:
  # Volume data baru untuk testing
  rental_pgdata_testing:

networks:
  # Network baru untuk testing
  rental_testing_network:
    name: rental_testing_network
    driver: bridge