version: '3.9'

services:
  backend:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - /var/www/html/rental-storage:/var/www/html/rental-storage
    restart: unless-stopped

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: rental
      POSTGRES_PASSWORD: rental
      POSTGRES_DB: rental
    ports:
      - "5432:5432"
    volumes:
      - rental-pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  rental-pgdata:
