const ACCESS_TOKEN_EXP = 2 * 60;
const REFRESH_TOKEN_EXP = 7 * 86400;
const JWT_NAME = "jwt";
const EXPIRY_DATE_MIDTRANS = 30;

export { ACCESS_TOKEN_EXP, REFRESH_TOKEN_EXP, JWT_NAME, EXPIRY_DATE_MIDTRANS };
