import {
  Fuel,
  Transmission,
  Vehicle_status,
  Vehicle_Types,
} from "@prisma/client";

export const vehiclesData = [
      {
        name: "Toyota Avanza G",
        type: Vehicle_Types.MPV,
        transmition: Transmission.AUTOMATIC,
        status: Vehicle_status.AVAILABLE,
        fuel: Fuel.PERTAMAXTURBO,
        brand: "Toyota",
        capacity: 7,
        kilometer: 25000,
        year: 2023,
        price_per_day: 350000.0,
        image_url: [
          "https://dummyimage.com/600x400/000/fff&text=Avanza+1",
          "https://dummyimage.com/600x400/ccc/000&text=Avanza+2",
        ],
        description:
          "Mobil keluarga andalan Indonesia. Irit, luas, dan nyaman untuk perjalanan dalam kota maupun luar kota.",
        color: "Silver Metallic",
      },
      {
        name: "Honda Brio Satya E",
        type: Vehicle_Types.HATCHBACK,
        transmition: Transmission.MANUAL,
        status: Vehicle_status.AVAILABLE,
        fuel: Fuel.PERTAMAXTURBO,
        brand: "Honda",
        capacity: 5,
        kilometer: 15000,
        year: 2024,
        price_per_day: 280000.0,
        image_url: ["https://dummyimage.com/600x400/ff0000/fff&text=Brio+1"],
        description:
          "City car lincah dan hemat bahan bakar. Cocok untuk mobilitas tinggi di perkotaan yang padat.",
        color: "Rallye Red",
      },
      {
        name: "Mitsubishi Xpander Ultimate",
        type: Vehicle_Types.MPV,
        transmition: Transmission.AUTOMATIC,
        status: Vehicle_status.RENTED,
        fuel: Fuel.PERTAMAXTURBO,
        brand: "Mitsubishi",
        capacity: 7,
        kilometer: 45000,
        year: 2022,
        price_per_day: 400000.0,
        image_url: ["https://dummyimage.com/600x400/333/fff&text=Xpander+1"],
        description:
          "MPV modern dengan desain futuristik, kabin senyap, dan fitur canggih untuk kenyamanan maksimal.",
        color: "Jet Black Mica",
      },
      {
        name: "Daihatsu Terios R",
        type: Vehicle_Types.SUV,
        transmition: Transmission.AUTOMATIC,
        status: Vehicle_status.AVAILABLE,
        fuel: Fuel.PERTAMAXTURBO,
        brand: "Daihatsu",
        capacity: 7,
        kilometer: 32000,
        year: 2022,
        price_per_day: 380000.0,
        image_url: ["https://dummyimage.com/600x400/fff/000&text=Terios+1"],
        description:
          "SUV tangguh dan serbaguna, siap menemani petualangan Anda di berbagai kondisi jalan.",
        color: "Icy White",
      },
      {
        name: "Hyundai Ioniq 5 Prime",
        type: Vehicle_Types.SUV,
        transmition: Transmission.AUTOMATIC,
        status: Vehicle_status.AVAILABLE,
        fuel: Fuel.PERTALITE,
        brand: "Hyundai",
        capacity: 5,
        kilometer: 8000,
        year: 2024,
        price_per_day: 950000.0,
        image_url: [
          "https://dummyimage.com/600x400/555/fff&text=Ioniq5+1",
          "https://dummyimage.com/600x400/ccc/000&text=Ioniq5+2",
        ],
        description:
          "Rasakan sensasi berkendara masa depan dengan SUV listrik ini. Hening, bertenaga, dan ramah lingkungan.",
        color: "Gravity Gold Matte",
      },
      {
        name: "Toyota Fortuner VRZ",
        type: Vehicle_Types.SUV,
        transmition: Transmission.AUTOMATIC,
        status: Vehicle_status.MAINTENANCE,
        fuel: Fuel.DEXLITE,
        brand: "Toyota",
        capacity: 7,
        kilometer: 65000,
        year: 2021,
        price_per_day: 800000.0,
        image_url: ["https://dummyimage.com/600x400/222/fff&text=Fortuner+1"],
        description:
          "SUV diesel mewah dan bertenaga, memberikan performa superior dan tampilan yang gagah di jalanan.",
        color: "Super White",
      },
      {
        name: "Honda HR-V SE",
        type: Vehicle_Types.SUV,
        transmition: Transmission.AUTOMATIC,
        status: Vehicle_status.AVAILABLE,
        fuel: Fuel.PERTAMAXTURBO,
        brand: "Honda",
        capacity: 5,
        kilometer: 22000,
        year: 2023,
        price_per_day: 550000.0,
        image_url: ["https://dummyimage.com/600x400/0000ff/fff&text=HRV+1"],
        description:
          "Compact SUV dengan desain elegan, kabin modern, dan pengalaman berkendara yang mulus.",
        color: "Sand Khaki Pearl",
      },
      {
        name: "Suzuki Ertiga Hybrid GX",
        type: Vehicle_Types.MPV,
        transmition: Transmission.MANUAL,
        status: Vehicle_status.AVAILABLE,
        fuel: Fuel.DEXLITE,
        brand: "Suzuki",
        capacity: 7,
        kilometer: 11000,
        year: 2024,
        price_per_day: 370000.0,
        image_url: [
          "https://dummyimage.com/600x400/808080/fff&text=Ertiga+Hybrid+1",
        ],
        description:
          "MPV hybrid efisien yang menawarkan konsumsi bahan bakar luar biasa tanpa mengorbankan ruang dan kenyamanan.",
        color: "Mellow Deep Red Pearl",
      },
      {
        name: "Wuling Air EV Long Range",
        type: Vehicle_Types.HATCHBACK,
        transmition: Transmission.AUTOMATIC,
        status: Vehicle_status.RENTED,
        fuel: Fuel.PERTALITE,
        brand: "Wuling",
        capacity: 4,
        kilometer: 9500,
        year: 2023,
        price_per_day: 300000.0,
        image_url: ["https://dummyimage.com/600x400/ffff00/000&text=AirEV+1"],
        description:
          "Mobil listrik perkotaan yang sempurna. Ringkas, mudah diparkir, dan ideal untuk perjalanan jarak pendek.",
        color: "Pristine White",
      },
      {
        name: "Toyota Camry V",
        type: Vehicle_Types.SEDAN,
        transmition: Transmission.AUTOMATIC,
        status: Vehicle_status.AVAILABLE,
        fuel: Fuel.PERTAMAXTURBO,
        brand: "Toyota",
        capacity: 5,
        kilometer: 38000,
        year: 2022,
        price_per_day: 750000.0,
        image_url: ["https://dummyimage.com/600x400/111/fff&text=Camry+1"],
        description:
          "Sedan premium yang menggabungkan kenyamanan, gaya, dan performa untuk pengalaman berkendara yang mewah.",
        color: "Attitude Black",
      },
      {
        name: "Toyota Raize GR Sport",
        type: Vehicle_Types.SUV,
        transmition: Transmission.AUTOMATIC,
        status: Vehicle_status.AVAILABLE,
        fuel: Fuel.PERTAMAXTURBO,
        brand: "Toyota",
        capacity: 5,
        kilometer: 21000,
        year: 2023,
        price_per_day: 420000.0,
        image_url: ["https://dummyimage.com/600x400/008080/fff&text=Raize+1"],
        description:
          "Compact SUV dengan mesin turbo yang memberikan pengalaman berkendara yang seru dan enerjik.",
        color: "Turquoise MM",
      },
      {
        name: "Daihatsu Sigra R",
        type: Vehicle_Types.MPV,
        transmition: Transmission.MANUAL,
        status: Vehicle_status.AVAILABLE,
        fuel: Fuel.PERTAMAXTURBO,
        brand: "Daihatsu",
        capacity: 7,
        kilometer: 52000,
        year: 2021,
        price_per_day: 290000.0,
        image_url: ["https://dummyimage.com/600x400/555555/fff&text=Sigra+1"],
        description:
          "LCGC 7-seater yang terjangkau dan praktis, pilihan tepat untuk keluarga hemat.",
        color: "Dark Grey Metallic",
      },
      {
        name: "Honda Civic RS",
        type: Vehicle_Types.SEDAN,
        transmition: Transmission.AUTOMATIC,
        status: Vehicle_status.MAINTENANCE,
        fuel: Fuel.PERTAMAXTURBO,
        brand: "Honda",
        capacity: 5,
        kilometer: 33000,
        year: 2022,
        price_per_day: 850000.0,
        image_url: [
          "https://dummyimage.com/600x400/ff4500/fff&text=Civic+RS+1",
        ],
        description:
          "Sedan sporty dengan mesin turbo, gaya agresif, dan serangkaian fitur teknologi modern.",
        color: "Ignite Red Metallic",
      },
      {
        name: "Toyota Alphard G",
        type: Vehicle_Types.MINIVAN,
        transmition: Transmission.AUTOMATIC,
        status: Vehicle_status.AVAILABLE,
        fuel: Fuel.PERTAMAXTURBO,
        brand: "Toyota",
        capacity: 7,
        kilometer: 40000,
        year: 2021,
        price_per_day: 1500000.0,
        image_url: ["https://dummyimage.com/600x400/f5f5dc/000&text=Alphard+1"],
        description:
          "Puncak kemewahan minivan. Menawarkan kenyamanan dan ruang tak tertandingi untuk perjalanan eksekutif atau VIP.",
        color: "Pearl White",
      },
      {
        name: "Mitsubishi Pajero Sport Dakar",
        type: Vehicle_Types.SUV,
        transmition: Transmission.AUTOMATIC,
        status: Vehicle_status.AVAILABLE,
        fuel: Fuel.PERTAMAXTURBO,
        brand: "Mitsubishi",
        capacity: 7,
        kilometer: 55000,
        year: 2021,
        price_per_day: 850000.0,
        image_url: [
          "https://dummyimage.com/600x400/c0c0c0/000&text=Pajero+Sport+1",
        ],
        description:
          "SUV premium 7-seater dengan mesin diesel bertenaga dan sistem 4WD canggih untuk kemampuan off-road superior.",
        color: "Sterling Silver Metallic",
      },
    ];